version: '3.8'

services:
  mysql-primary:
    image: biarms/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: notprodpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
    volumes:
      - primary-data:/var/lib/mysql
      - ./mysql-init/init-primary.sql:/docker-entrypoint-initdb.d/init-primary.sql
      - ./mysql-config/primary.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - mysql-network

  mysql-replica:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: notprodpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - replica-data:/var/lib/mysql
      - ./mysql-init/init-replica.sql:/docker-entrypoint-initdb.d/init-replica.sql
      - ./mysql-init/setup-replica.sh:/docker-entrypoint-initdb.d/setup-replica.sh
      - ./mysql-config/replica.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - mysql-primary
    networks:
      - mysql-network
  mysql-destination:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: notprodpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    volumes:
      - destination-data:/var/lib/mysql
      - ./mysql-config/destination.cnf:/etc/mysql/conf.d/my.cnf
    depends_on:
      - mysql-primary
    networks:
      - mysql-network

volumes:
  primary-data:
  replica-data:
  destination-data:

networks:
  mysql-network:
